let received = 0;
let sales = [];
let expenses = [];
let purchase = [];
let udhaar = [];
let pisai = [];
let payments = [];
let lastEntries = [];
let stock = 0;
let page = "dashboard";
let isLoggedIn = localStorage.getItem("chakkiLoggedIn") === "true";
let liveSyncUnsubscribe = null;
